repos:
  - repo: local
    hooks:
      - id: mkdocs-build
        name: Build MkDocs site
        entry: mkdocs build --strict
        language: system
        files: \.(py|md|css|ya?ml)$
        pass_filenames: false
        fail_fast: true