site_name: Scott Saenz | Data Engineer & Analytics Enthusiast
site_author: Scott Saenz
site_url: https://www.scottsaenz.com
site_description: Personal website for Scott Saenz
theme:
  name: material
  features:
    - navigation.instant
    #- navigation.tabs
    #- navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      accent: '#f5c97b'     # gold from logo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      accent: '#aacdcc'     # light blue from logo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: src/imgs/icon.svg
nav:
  - Home: index.md
  - About: about.md
  - Blog:
     - blog/index.md
  - Training Plans:
      - Advanced Python Training: training/advanced-python-training.md
docs_dir: docs
extra_css:
  - css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scottsaenz
plugins:
  - search
  - blog:
      archive: false
      post_url_format: "{categories}/{slug}"
  #- mkdocs-jupyter
  #- glightbox
  #- table-reader
  - git-revision-date-localized
  #- awesome-pages
  #- minify
  #- section-index

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic:
      mode: inline
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
  - js/mermaid-config.js



