site_name: Scott Saenz | Data Engineer & Analytics Enthusiast
site_author: Scott Saenz
site_url: https://www.scottsaenz.com
site_description: Personal website for Scott Saenz
theme:
  name: material
  features:
    - navigation.instant
    #- navigation.tabs
    #- navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: '#509270'    # green from logo
      accent: '#f5c97b'     # gold from logo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: '#03182a'    # dark blue from logo
      accent: '#aacdcc'     # light blue from logo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - Blog Index: blog/index.md
      - Migrating from Docusaurus to MkDocs: blog/20250601.md
  - Training Plans:
      - Advanced Python Training: training/advanced-python-training.md
docs_dir: docs
extra_css:
  - css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scottsaenz
plugins:
  - search
  - blogging:
      paging: false
  - mkdocs-jupyter
  - glightbox
  - table-reader
  - mermaid2
  - git-revision-date-localized
  #- awesome-pages
  - minify
  - section-index

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic:
      mode: inline
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
#extra_javascript:
#  - javascripts/mathjax.js
#  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
logo: src/imgs/icon.svg
