name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate git revision dates

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install .

      - name: Build MkDocs site
        run: .venv/bin/mkdocs build
        env:
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync site/ s3://scottsaenz.com --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1E72T1VG0T1TU --paths "/*"

      - name: Wait for CloudFront invalidation
        run: |
          echo "Waiting for CloudFront cache invalidation to complete..."
          sleep 30
          
      - name: Submit sitemap to Bing Webmaster Tools
        run: |
          echo "Submitting sitemap to Bing Webmaster Tools..."
          curl -X GET \
            "https://www.bing.com/ping?sitemap=https://www.scottsaenz.com/sitemap.xml" \
            -H "User-Agent: GitHub-Actions-Bot/1.0" \
            -H "Content-Length: 0" \
            --fail-with-body || echo "Bing sitemap submission failed, but continuing..."

      - name: Verify site accessibility
        run: |
          echo "Verifying site is accessible..."
          curl -I "https://www.scottsaenz.com" \
            -H "User-Agent: GitHub-Actions-Bot/1.0" \
            --fail-with-body

      - name: Check sitemap accessibility
        run: |
          echo "Verifying sitemap is accessible..."
          curl -I "https://www.scottsaenz.com/sitemap.xml" \
            -H "User-Agent: GitHub-Actions-Bot/1.0" \
            --fail-with-body

      - name: Deployment Summary
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "✅ Site built with MkDocs"
          echo "✅ Files synced to S3"
          echo "✅ CloudFront cache invalidated"
          echo "✅ Sitemap submitted to search engines"
          echo "✅ Site accessibility verified"
          echo "🌐 Site available at: https://www.scottsaenz.com"
